### ISSUE TITLE
Consider allowing the blocklist to include private domains from the public suffix list

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-list-creation#102]
In #26 we started filtering public suffixes from the blacklist. For true public suffixes this makes sense (like `.com`), but for private suffixes added to the public suffix list it might not. For a comparison between the two see [the tldextract library](https://github.com/john-kurkowski/tldextract/tree/cd911e3af960808f9ed9818197d405b06b36a89e#public-vs-private-domains).

Let's say I'm a tracker trying to work around ETP in an adversarial way. I register my domain `tracker.example` as a private domain on the PSL. Now, I generate a new subdomain for every site that embeds my domain `xyz.tracker.example`, `abc.tracker.example`, and so on. If a browser that does list-based blocking respects the private section of the PSL, then that browser will have to add every single subdomain of `tracker.example` to the blocklist to effectively block my content. 

Note that Firefox currently does not respect the PSL boundary when checking if a domain matches the url-classifier ([Bug 1203635](https://bugzilla.mozilla.org/show_bug.cgi?id=1203635)), but we may find a reason we need to change that in the future. If we do, I think it makes sense to allow public suffixes on the list and ensure that the url-classifier checks the public suffix.

**Comment by say-yawn** [comment]
@boolean5

**Comment by englehardt** [comment]
Some additional context here. We originally started skipping public suffixes because of [Bug 1202082](https://bugzilla.mozilla.org/show_bug.cgi?id=1202082). Basically tracking protection would match any public suffix on the blocklist because of [Bug 1203635](https://bugzilla.mozilla.org/show_bug.cgi?id=1203635), but our entitylist would fail to apply because the entity list only checks public suffix + 1 (aka eTLD+1). Removing public suffixes from the blocklist was one way to fix that.

In [Bug 1580416](https://bugzilla.mozilla.org/show_bug.cgi?id=1580416) we changed the url classifier to check both the public suffix and public suffix +1 when checking for allowlisted domains on the entitylist. See also [this code comment](https://searchfox.org/mozilla-central/rev/3d39d3b7dd1b2be30692d4541ea681614e34c786/toolkit/components/url-classifier/LookupCache.cpp#468-474). Thus, it's now safe to have public suffix domains on the blocklist.

I've verified that both`googleapis.com` and `cloudfront.net` are on the entitylist, so the type of breakage Francois saw in [Bug 1202082](https://bugzilla.mozilla.org/show_bug.cgi?id=1202082) should no longer be present. We should verify this in stage if possible.

**Comment by boolean5** [comment]
The latest version of `publicsuffixlist`, which is the library we are currently using, has an `only_icann` keyword argument that can be used to only check against the public section of the Public Suffix List. 

Commit 3fd850097 in https://github.com/mozilla-services/shavar-list-creation/pull/141 makes `add_domain_to_list` raise a `ValueError` for domains in the public section of the PSL but permits domains in the private section of the PSL to be written to the blocklist. @englehardt, is this what you had in mind?

**Comment by englehardt** [comment]
> The latest version of `publicsuffixlist`, which is the library we are currently using, has an [`only_icann` keyword argument](https://github.com/ko-zu/psl#icann-and-private-suffixes) that can be used to only check against the public section of the Public Suffix List.
> 
> Commit [3fd8500](https://github.com/mozilla-services/shavar-list-creation/commit/3fd8500976c05ead89cb43ca3a58e7b6b0e0df5c) in #141 makes `add_domain_to_list` raise a `ValueError` for domains in the public section of the PSL but permits domains in the private section of the PSL to be written to the blocklist. @englehardt, is this what you had in mind?

Yes that's what I had in mind. I added one suggestion in the PR to point back to this issue for context.
