### ISSUE TITLE
Make Python3 compatible

### ISSUE THREAD

**Issue by birdsarah** [mozilla-services/shavar-list-creation#108]
Just a note that this library is not currently py3 compatible.

I took a quick stab at it, but it'll be a little more than a very quick job due to unicode/bytes drama.

Time to fix will be dependent on whether can just upgrade to py3 or whether it needs to maintain py2 compatibility.

Initial stuff:
* use six for imports of ConfigParser and urllib
* use requests for getting instead of urlopen

```diff
diff --git a/lists2safebrowsing.py b/lists2safebrowsing.py
index 39385c5..4947050 100755
--- a/lists2safebrowsing.py
+++ b/lists2safebrowsing.py
@@ -1,14 +1,14 @@
 #!/usr/bin/env python

-import ConfigParser
 import hashlib
-import json
 import os
 import re
 import requests
 import sys
 import time
-import urllib2
+
+from six.moves import configparser as ConfigParser
+from six.moves.urllib.parse import quote, unquote
 
 from packaging import version
 from publicsuffixlist import PublicSuffixList
@@ -66,7 +66,7 @@ def get_list_url(config, section, key):
 def load_json_from_url(config, section, key):
     url = get_list_url(config, section, key)
     try:
-        loaded_json = json.loads(urllib2.urlopen(url).read())
+        loaded_json = requests.get(url).json()
     except Exception:
         sys.stderr.write("Error loading %s\n" % url)
         sys.exit(-1)
@@ -91,7 +91,7 @@ def canonicalize(d):
     # repeatedly unescape until no more hex encodings
     while (1):
         _d = d
-        d = urllib2.unquote(_d)
+        d = unquote(_d)
         # if decoding had no effect, stop
         if (d == _d):
             break
@@ -120,7 +120,7 @@ def canonicalize(d):
     _path = ""
     for i in path:
         if (ord(i) <= 32 or ord(i) >= 127 or i == '#' or i == '%'):
-            _path += urllib2.quote(i)
+            _path += quote(i)
         else:
             _path += i

@@ -400,10 +426,10 @@ def get_tracker_lists(config, section, chunknum):
         allowlist_url = None
     # TODO: refactor into: def get_allowed_domains(allowlist_url)
     if allowlist_url:
-        for line in urllib2.urlopen(allowlist_url).readlines():
+        for line in requests.get(allowlist_url).iter_lines():
             line = line.strip()
             # don't add blank lines or comments
-            if not line or line.startswith('#'):
+            if not line or line.startswith(b'#'):
                 continue

     # Write blocklist in a format compatible with safe browsing
@@ -590,10 +619,10 @@ def main():
             blocked = set()
             blocklist_url = config.get(section, "blocklist")
             if blocklist_url:
-                for line in urllib2.urlopen(blocklist_url).readlines():
+                for line in requests.get(blocklist_url).iter_lines():
                     line = line.strip()
                     # don't add blank lines or comments
-                    if not line or line.startswith('#'):
+                    if not line or line.startswith(b'#'):
                         continue
                     blocked.add(line)
 
diff --git a/publish2cloud.py b/publish2cloud.py
index f71b56e..39e5cb8 100644
--- a/publish2cloud.py
+++ b/publish2cloud.py
@@ -1,4 +1,4 @@
-import ConfigParser
+from six.moves import configparser as ConfigParser
 import hashlib
 import os
 import requests
diff --git a/requirements.txt b/requirements.txt
index 02a9871..63fe970 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,7 @@
 boto==2.40.0
 publicsuffixlist==0.4.0
-requests==2.10.0
+requests==2.22.0
 trackingprotection_tools==0.4.6
 packaging==19.2
 setuptools==40.8.0
+six==1.13.0
```

**Comment by shreyagupta30** [comment]
Hello @birdsarah! I am an outreachy applicant and was looking for a good first bug to fix for my contribution period. This issue caught my eye. I would like to work on this. Could you please guide me a little about this project.

**Comment by englehardt** [comment]
> Hello @birdsarah! I am an outreachy applicant and was looking for a good first bug to fix for my contribution period. This issue caught my eye. I would like to work on this. Could you please guide me a little about this project.

Redirecting this request to @skim1102

**Comment by skim1102** [comment]
@englehardt thanks for bringing me into the conversation.

@shreyagupta30 I am glad to hear this caught your attention, however for the contribution stage for Outreachy Internship we are only accepting pull requests for issues that are labeled `good first bug`. If you are having a hard time figuring out which issues are good to work on I recommend reading the documentations on https://www.outreachy.org/apply/project-selection/

**Comment by boolean5** [comment]
Leaving a note here that once we upgrade to Python 3 we should use the most recent version of `pytest`. Right now `pytest` is pinned to the last version that supports Python 2.7.

**Comment by say-yawn** [comment]
Dependent on completion of:
- [ ] https://github.com/mozilla-services/shavar-list-creation/issues/130
- [ ] https://github.com/mozilla-services/shavar-list-creation/issues/129

**Comment by say-yawn** [comment]
Dependent on completion of: 
- [ ] https://github.com/mozilla-services/shavar-list-creation/issues/132

**Comment by boolean5** [comment]
Leaving a couple more notes:
- https://github.com/mozilla-services/shavar-list-creation/pull/141 introduced `mock` as a dependency, but once we switch to Python 3 we can remove it. This is because in Python 3 `mock` is part of the standard library. We will just have to replace `from mock import call, patch, mock_open` with `from unittests.mock import call, patch, mock_open`.
- When we migrate to Python 3, we should update the CircleCi config file to use a docker image with Python 3, instead of `circleci/python:2.7`, which we are currently using.
