### ISSUE TITLE
Installation on mac os fails using requirements.txt

### ISSUE THREAD

**Issue by dtlight** [mozilla-services/shavar-list-creation#119]
**The issue:** trouble installing via requirements.txt which throws an installation error for plyvel.
**Operating system:** Mac OS
**Solution:** install leveldb via homebrew by issuing the command "brew install leveldb", then run requirements.txt
**Action:** Is it worth adding this to the readme instructions for the sake of future outreachy or other contributors?

**Comment by skim1102** [comment]
Thanks for bringing this issue up. I recommend leaving this issue open for few weeks and if we get other contributors experiencing the same issue (if you are please comment here) we should go ahead and update the README.

**Comment by HarshitSohaney** [comment]
I don't think this issue is relevant anymore, the installation works as expected on macos. I think we can close this
