### ISSUE TITLE
Add unittests for code in lists2safebrowsing.py

### ISSUE THREAD

**Issue by say-yawn** [mozilla-services/shavar-list-creation#129]
Currently there are no unittests for lists2safebrowsing.py and having unittests will ensure that the scripts work as expected. 

# Acceptance Criteria
- [x] #135 is completed
- [x] #136 is completed
- [x] #137 is completed (PR #142)
- [x] Integrate with CircleCI (PR https://github.com/mozilla-services/shavar-list-creation/pull/140)
- [x] Configure coverage reporting (PR https://github.com/mozilla-services/shavar-list-creation/pull/152)
- [x] https://github.com/mozilla-services/shavar-list-creation/pull/143 is merged
- [x] https://github.com/mozilla-services/shavar-list-creation/pull/154 is merged

**Comment by yamini27** [comment]
Ma'am, I have made a pull request for this issue which is https://github.com/mozilla-services/shavar-list-creation/commit/9fef0fe1611868931ed5a46be5623c32296c77ea . Please review it and suggest further changes. Thank you!

**Comment by skim1102** [comment]
@yamini27 Hello! Thank you for filing a commit to add unittests to shavar-list-creation. Here are some recommendations:

- I think it's best to use [pytest](https://docs.pytest.org/en/latest/getting-started.html) for the testing framework
- It would be nice to have a `test` folder for `test_lists2safebrowsing.py` and `test_publish2cloud.py` files where each files are testing code in the respective `lists2safebrowsing.py` and `publish2cloud.py` files

Additionally, I would appreciate it if you can create a branch from your forked repo and create a [work-in-progress PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to further discuss the code. Thank you!

**Comment by HarshitSohaney** [comment]
All tasks are completed
