### ISSUE TITLE
create setup.py

### ISSUE THREAD

**Issue by dave-light** [mozilla-services/shavar-list-creation#131]
To achieve https://github.com/mozilla-services/shavar-prod-lists/pull/156 3 scripts are needed from shavar-list-creation. Since it's not a best practice to duplicate the same code, i've decided to install the shavar-list-creation modules via pip as per https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source?noredirect=1&lq=1 

I'm unable to install at the moment because setup.py doesn't exist. I'll submit a pull request to add it, unless you see a better way @skim1102

**Comment by skim1102** [comment]
@dave-light I don't think shavar-list-creation should be packaged. I would instead suggest using the existing code in shavar-list-creation to get inspiration on how to achieve the same on shavar-prod-lists. Moving the discussion back to https://github.com/mozilla-services/shavar-prod-lists/pull/156
