### ISSUE TITLE
Add unit test for canonicalize

### ISSUE THREAD

**Issue by boolean5** [mozilla-services/shavar-list-creation#135]
We should add a unit test for the `canonicalize` function in `lists2safebrowsing.py`. We can probably use the suggested test cases from https://web.archive.org/web/20160422212049/https://developers.google.com/safe-browsing/developers_guide_v2#Canonicalization

**Comment by boolean5** [comment]
Running the test cases from the above link may have uncovered a few bugs in the canonicalization implementation. I'll describe them here briefly. The question is, which of them are indeed bugs and which are intentional design choices?

1. The following 3 assertions are all failing with 
`AssertionError: assert ' leadingspace.com/' == '%20leadingspace.com/'`:

        assert canonicalize("http:// leadingspace.com/") == "%20leadingspace.com/"
        assert canonicalize("http://%20leadingspace.com/") == "%20leadingspace.com/"
        assert canonicalize("%20leadingspace.com/") == "%20leadingspace.com/"

    The [Safe Browsing v2 documentation on canonicalization](https://web.archive.org/web/20160422212049/https://developers.google.com/safe-browsing/developers_guide_v2#Canonicalization) mentions that we should "percent-escape all characters in the URL which are <= ASCII 32, >= 127, "#", or "%"". In `canonicalize()` [we are only applying this to the path part of the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L119L129) and not the whole url. As a result, spaces that are found in the host part of the url are not percent-escaped.

2. `assert canonicalize("http://www.gotaport.com:1234/") ==
"www.gotaport.com:1234/"`
fails with `AssertionError: assert 'www.gotaport.com/' ==
'www.gotaport.com:1234/'`

    The Safe Browsing v2 documentation doesn't mention anything about removing ports. However, in `canonicalize()` [the port is removed when the hostname is extracted from the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L99L106).

    I suspect that the port is dropped for the same [reason that the scheme is](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L127L128). In this case, I think it would be worth a comment.

3. `assert canonicalize("  http://www.google.com/  ") == "www.google.com/"` fails with:

        AttributeError: 'NoneType' object has no attribute 'group'
        lists2safebrowsing.py:106: AttributeError

    This is because [the regular expression used to extract the host and the path from the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L104) cannot match urls with preceding spaces. We could either change the regular expression or use `strip()` to get rid of preceding and trailing spaces.


4. `assert canonicalize("http://www.google.com/blah/..") == "www.google.com/"`
fails with `AssertionError: assert 'www.google.com/blah/..' == 'www.google.com/'`

    According to the Safe Browsing v2 documentation, we should resolve "/../" by removing it along with the preceding path component.

5. `assert canonicalize("http://3279880203/blah") == "195.127.0.11/blah"` fails
with `AssertionError: assert '3279880203/blah' == '195.127.0.11/blah'`

    The Safe Browsing v2 docs mention the following:
"If the hostname can be parsed as an IP address, it should be normalized to 4 dot-separated decimal values. The client should handle any legal IP- address encoding, including octal, hex, and fewer than 4 components."

**Comment by say-yawn** [comment]
>     1. The following 3 assertions are all failing with
>        `AssertionError: assert ' leadingspace.com/' == '%20leadingspace.com/'`:
>        ```
>         assert canonicalize("http:// leadingspace.com/") == "%20leadingspace.com/"
>         assert canonicalize("http://%20leadingspace.com/") == "%20leadingspace.com/"
>         assert canonicalize("%20leadingspace.com/") == "%20leadingspace.com/"
>        ```
>        
>        
>        The [Safe Browsing v2 documentation on canonicalization](https://web.archive.org/web/20160422212049/https://developers.google.com/safe-browsing/developers_guide_v2#Canonicalization) mentions that we should "percent-escape all characters in the URL which are <= ASCII 32, >= 127, "#", or "%"". In `canonicalize()` [we are only applying this to the path part of the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L119L129) and not the whole url. As a result, spaces that are found in the host part of the url are not percent-escaped.

Let's bring this up in our weekly meeting
>     2. `assert canonicalize("http://www.gotaport.com:1234/") == "www.gotaport.com:1234/"`
>        fails with `AssertionError: assert 'www.gotaport.com/' == 'www.gotaport.com:1234/'`
>        The Safe Browsing v2 documentation doesn't mention anything about removing ports. However, in `canonicalize()` [the port is removed when the hostname is extracted from the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L99L106).
>        I suspect that the port is dropped for the same [reason that the scheme is](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L127L128). In this case, I think it would be worth a comment.
Need to confirm this in the weekly meeting

>     3. `assert canonicalize("  http://www.google.com/  ") == "www.google.com/"` fails with:
>        ```
>         AttributeError: 'NoneType' object has no attribute 'group'
>         lists2safebrowsing.py:106: AttributeError
>        ```
>        
>        
>        This is because [the regular expression used to extract the host and the path from the url](https://github.com/mozilla-services/shavar-list-creation/blob/master/lists2safebrowsing.py#L104) cannot match urls with preceding spaces. We could either change the regular expression or use `strip()` to get rid of preceding and trailing spaces.
There was a `TODO` comment to use `urlparse`. I think It's worth looking into that to fix this. If you think it will take longer than a day to update the code to use `urlparse` we can create a separate issue and for not `strip()` for spaces before and after the domain. 

>     4. `assert canonicalize("http://www.google.com/blah/..") == "www.google.com/"`
>        fails with `AssertionError: assert 'www.google.com/blah/..' == 'www.google.com/'`
>        According to the Safe Browsing v2 documentation, we should resolve "/../" by removing it along with the preceding path component.
Need to confirm in meeting

>     5. `assert canonicalize("http://3279880203/blah") == "195.127.0.11/blah"` fails
>        with `AssertionError: assert '3279880203/blah' == '195.127.0.11/blah'`
>        The Safe Browsing v2 docs mention the following:
>        "If the hostname can be parsed as an IP address, it should be normalized to 4 dot-separated decimal values. The client should handle any legal IP- address encoding, including octal, hex, and fewer than 4 components."
Not sure if we actually need this. Let's confirm in meeting.

cc @englehardt

**Comment by say-yawn** [comment]
4. Fourth case should just throw and error. Alternatively we can use URL join but we should fail and display an error that our logic does not support this case--that way we can use this on shavar-prod-lists CircleCI check and our Disconnect partners can see why it failed)
5. Use URLParse and if the host name is empty throw an error (we are assuming that the numbers will be considered as a part of the scheme)

**Comment by boolean5** [comment]
>>> from urlparse import urlparse
    >>> urlparse("http:// leadingspace.com/").hostname
    ' leadingspace.com'
    >>> urlparse("http://www.gotaport.com:1234/").hostname
    'www.gotaport.com'
    >>> urlparse(" http://www.google.com/ ")
    ParseResult(scheme='', netloc='', path=' http://www.google.com/ ', params='',
    query='', fragment='')

As can be seen above, `urlparse`:

1. Preserves spaces in the hostname
2. Does not include the port in the hostname
3. If there are leading spaces `urlparse` returns an empty hostname and thinks that 
`" http://www.google.com/ "` is the path. This means that even if we use `urlparse` in `canonicalize()` we will still have to use `strip()` before.

> There was a TODO comment to use urlparse. I think It's worth looking into that to fix this. If you think it will take longer than a day to update the code to use urlparse we can create a separate issue and for not strip() for spaces before and after the domain.

Since `urlparse` won't solve any of the problems we discussed in this issue, I would suggest opening an issue and getting back to this later.

**Comment by boolean5** [comment]
> (1) Need to talk with Dimi (I'll reach out to him in #shavar). FYI if we copy paste that URL Firefox considers this as a search, not a URL.

Do we have an update on this? We should keep in mind that this is not just about spaces but any character that is <= ASCII 32, >= 127, "#", or "%".

**Comment by say-yawn** [comment]
Creating a separate issue for using url-parse sounds good to me.
