### ISSUE TITLE
cloudfront.net is added to tracking content block list

### ISSUE THREAD

**Issue by ltm** [mozilla-services/shavar-list-creation#153]
It looks like cloudfront.net (the Amazon CloudFront domain) is added to the content-track-digest256 block list as a result of #141 and specifically commit 8f805a7081d017c5cd1a500c56b1ab4a27f76b44. This causes several sites (such as circleci.com and Atlassian Jira) to break when the "Level 2 block list" is used in Firefox.

```
$ cp sample_shavar_list_creation.ini shavar_list_creation.ini
$ ./lists2safebrowsing.py
...
$ grep cloudfront.net content-track-digest256.log
[m] cloudfront.net >> cloudfront.net/
[canonicalized] cloudfront.net/

$ git checkout 599e8c8
...
HEAD is now at 599e8c8 Merge pull request #147 from mozilla-services/configure-circleci
$ ./lists2safebrowsing.py
...
$ grep cloudfront.net content-track-digest256.log
[Public Suffix] cloudfront.net; Skipping.
```

**Comment by say-yawn** [comment]
Hi @ltm thank you for submitting this issue. I will look into this.

**Comment by say-yawn** [comment]
Related to https://github.com/mozilla-services/shavar-list-creation/issues/102

**Comment by ltm** [comment]
Thanks, @say-yawn. Reading #102 it looks like adding cloudfront.net to the block list was intentional. However, using Firefox 78 with "Level 2 block list" content tracking enabled, I've experienced several major sites, such as Atlassian Jira, circleci.com, and nextdoor.com break entirely.

**Comment by say-yawn** [comment]
Tested on https://nextdoor.com, https://www.atlassian.com/software/jira, and https://circleci.com/ but was unable to see (1) cloudfront.net was blocked under content-tracking on those sites and (2) unable to find breakages.
@ltm can you elaborate more on where you found the breakages using what version of Firefox? Any screenshots, link, or steps to reproduce the breakage would be appreciated.

**Comment by ltm** [comment]
@say-yawn I'm running Firefox 78.0.2 (Build ID 20200708170202) on macOS Catalina:

<img width="641" src="https://user-images.githubusercontent.com/714118/87439014-3f9e0480-c5be-11ea-9c56-6ada87e08e59.png">

I have all tracking protection enabled:

<img width="673" src="https://user-images.githubusercontent.com/714118/87439008-3d3baa80-c5be-11ea-80a1-120295203c67.png">

Including the Level 2 block list:

<img width="864" src="https://user-images.githubusercontent.com/714118/87438999-3ad95080-c5be-11ea-9f2e-a1b9b8140a28.png">

This is what circleci.com looks like. Note that both cloudfront.net and googleapis.com are blocked:

<img width="1024" src="https://user-images.githubusercontent.com/714118/87439036-475da900-c5be-11ea-9fa6-5de586f493e7.png">

The web inspector shows the domains blocked as Tracking:

<img width="949" src="https://user-images.githubusercontent.com/714118/87438961-2eed8e80-c5be-11ea-96c3-c5d3564891c1.png">

**Comment by ltm** [comment]
These are the related preferences. If I reset urlclassifier.trackingTable to the default value (i.e. moztest-track-simple,ads-track-digest256,social-track-digest256,analytics-track-digest256) which I believe is equivalent to "Level 1 block list", then I no longer have the issue.

Preference Name                                | Value
---------------------------------------------- | -------------
urlclassifier.trackingAnnotationSkipURLs       | google.com/recaptcha/,*.google.com/recaptcha/
urlclassifier.trackingAnnotationTable          | moztest-track-simple,ads-track-digest256,social-track-digest256,analytics-track-digest256,content-track-digest256
urlclassifier.trackingAnnotationWhitelistTable | moztest-trackwhite-simple,mozstd-trackwhite-digest256,google-trackwhite-digest256 
**urlclassifier.trackingTable**                | **moztest-track-simple,ads-track-digest256,social-track-digest256,analytics-track-digest256,content-track-digest256**
urlclassifier.trackingWhitelistTable           | moztest-trackwhite-simple,mozstd-trackwhite-digest256,google-trackwhite-digest256

**Comment by say-yawn** [comment]
@ltm thank you for the detailed explanation and STR. Unfortunately, we no longer support the Level 2 Blocklist for Strict Enhanced Tracking Protection. The list chooser UI has been removed for new users. See [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1568900#c3) for more info.
