### ISSUE TITLE
Filter out public suffixes from the blacklist

### ISSUE THREAD

**Issue by fmarier** [mozilla-services/shavar-list-creation#26]
As an extra precaution, we should ensure that blacklists don't contain any bare [public suffixes](https://publicsuffix.org/). For example, we don't want to start blocking `.com` if that gets onto the list by mistake.

Something like `.com` is obvious and would most likely get caught by our manual review process, but others aren't. `googleapis.com` is currently [on the list](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json#L7486) and that's [preventing resources from being whitelisted](https://bugzilla.mozilla.org/show_bug.cgi?id=1202082).

**Comment by fmarier** [comment]
I found a [Python library](https://pypi.python.org/pypi/publicsuffix) that can do the public suffix checks. Here's the test I used to make sure it works:

```
$ apt install python-publicsuffix publicsuffix
$ cat - > test.py
import codecs
psl_file = codecs.open('/usr/share/publicsuffix/effective_tld_names.dat', encoding='utf8')
from publicsuffix import PublicSuffixList
psl = PublicSuffixList(psl_file)
print psl.get_public_suffix("content.googleapis.com")
$ python ./test.py
'content.googleapis.com'
```

**Comment by fmarier** [comment]
Note: we should not make any changes to the list creation script until the diary study is over.

**Comment by groovecoder** [comment]
Maybe I don't understand the PSL library, but I'm not sure its `get_public_suffix` will help us prune our blocklist of bare public suffixes.

We have `googleapis.com` in our blocklist, and `psl.get_public_suffix("googleapis.com")` returns `googleapis.com`, which we already know ... so I don't know that it helps us filter that out? In addition, `psl.get_public_suffix("facebook.com")` returns `facebook.com` so it seems like this library is only good for getting bare public suffixes for domains that include sub-domains.

I think it will be easier and more accurate to just check the psl list without the library. Or just use the `fetch` helper of the library ...

**Comment by groovecoder** [comment]
I found [`publicsuffixlist` library](https://pypi.python.org/pypi/publicsuffixlist) far more helpful. Easy to implement and it successfully caught `googleapis.com` and `cloudfront.net`:

https://github.com/mozilla-services/shavar-list-creation/commit/20cd07edabdbdad9d4880bdd385a3286ccad2609

**Comment by kontaxis** [comment]
You might be able to fork https://github.com/kontaxis/eTLDplusOne and slightly adapt it.

**Comment by fmarier** [comment]
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1202082.
