### ISSUE TITLE
Ensure property and resource hosts only appear in a single domain

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/shavar-list-creation#40]
While processing the entity list, ensure that each property & resource domain only occurs in a single entity, to prevent down-stream bugs where a duplicate resource domain might be mis-identified as belonging to an entity.

See https://github.com/mozilla/blok/pull/104#discussion_r74635486

**Comment by fmarier** [comment]
Maybe https://github.com/mozilla-services/shavar-prod-lists/blob/master/scripts/json_verify.py would be a better place for this test? It would catch these errors earlier.

**Comment by groovecoder** [comment]
Oops, yeah I meant to put this into that repo.
