### ISSUE TITLE
Automatically add the trailing slash if it's missing

### ISSUE THREAD

**Issue by fmarier** [mozilla-services/shavar-list-creation#45]
Safe Browsing requires a trailing slash for bare domains (i.e. `example.com` is invalid but `example.com/` or `example.com/foo.html` are fine).

The list creation script should either break when it encounters `example.com` or (ideally) it should automatically add the slash.

**Comment by LilyLME** [comment]
@skim1102 please can you look at this an assign to me with some more context? 
Does not look like a complex issue 😊

**Comment by boolean5** [comment]
This looks like it can be closed, as `canonicalize()` adds a trailing slash when there isn't one.

**Comment by HarshitSohaney** [comment]
@artines1 we can close this one as per the last comment
