### ISSUE TITLE
Update the blocklist more than every 12 hours

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar-list-creation#7]
Yesterday after noon PT I pushed an updates to the exception list: https://github.com/mozilla-services/shavar-list-exceptions/commits/master

A couple hours later I pulled the blocklist, and the timestamp was noon PT according to https://github.com/monicachew/shavar-test. The changes were picked up at midnight PT, so it looks like this cron may be running only every 12 hours? The alternative explanation is that shavar is only refreshing the blocklist every 12 hours, I'm not sure.

@rfk @rtilder @ckolos

**Comment by ckolos** [comment]
there was a bug on our side. fixed.
